name: Version Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Node commands
        uses: actions/setup-node@v3

      - run: yarn install

      - run: yarn test

      - run: yarn publish
        if: steps.get_version.outputs.prerelease == ''
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: yarn publish --tag next
        if: steps.get_version.outputs.prerelease != ''
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
